serverAddr = ""
serverPort = 7000
auth.method = "token"
auth.token = ""

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "192.168.1.8"
localPort = 22
remotePort = 7001


[[proxies]]
name = "web"
type = "tcp"
localIP = "portal"
localPort = 3000
remotePort = 7002



